"""Column helpers shared by every model."""

import uuid
from datetime import datetime

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column


def uuid_pk() -> Mapped[uuid.UUID]:
    """UUID primary key generated by the database, not by the application."""
    return mapped_column(UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()"))


def created_now() -> Mapped[datetime]:
    return mapped_column(sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now())


def fk(target: str, *, nullable: bool) -> Mapped[uuid.UUID]:
    """A UUID foreign key. Every one is RESTRICT: no row the history depends on is deleted by cascade."""
    return mapped_column(
        UUID(as_uuid=True), sa.ForeignKey(target, ondelete="RESTRICT"), nullable=nullable
    )
